### ISSUE TITLE
[feature request] add an option to keep mode line

### ISSUE THREAD

**Issue by Elilif** [liuyinz/mini-echo.el#10]
Thank you for your package! 

I would like to keep mode line while enabling `mini-ehco-mode`. Do you mind adding an option to support it?

**Comment by liuyinz** [comment]
Emm.. No plan for that.
you can fork and just comment the function calling of `mini-echo-hide-modeline` info the code block below.
https://github.com/liuyinz/mini-echo.el/blob/ea1fdc36d169f2a4a12bf265db879b9bf87088d6/mini-echo.el#L401-L414
