### ISSUE TITLE
Total line count in buffer position

### ISSUE THREAD

**Issue by orazdow** [liuyinz/mini-echo.el#13]
I was looking for a way to get something like mini-echo-position-format  "%l:%t" with t as the total line count, but did not figure it out.
Is there a way to customize this?

thanks

**Comment by liuyinz** [comment]
`format-mode-line` do not have this to calculate total line number of current buffer, you need to define such a segment to call function to calculate it instead.

**Comment by orazdow** [comment]
I have another quick question actually. What sets the color for the status character after the buffer name? I was looking for a face that I could set to change or decolorize it, but didn't find it.
