### ISSUE TITLE
Disable modeline in buffer with fundamental mode

### ISSUE THREAD

**Issue by JiaweiChenC** [liuyinz/mini-echo.el#16]
I am using doom emacs. When I enable mini-echo mode,  the buffers with fundamental mode will still show modeline, I think this might be a issue due to the use of hide-mode-line-mode package, which cannot address \*buffer\* with fundamental mode. Is there an way to solve that? 
It is a issue when I want to use the scratch buffer in doom emacs, where the modeline will show up when I popup the scratch buffer
<img width="868" alt="image" src="https://github.com/user-attachments/assets/8fc8b0b6-4e61-4db0-8f8c-5140578d9a2f">
I would appreciate any sugguestions for that!

**Comment by liuyinz** [comment]
how about  `(setq hide-mode-line-excluded-modes nil)` ?

**Comment by JiaweiChenC** [comment]
Thank you for your response! I think (set hide-mode-line-exclude-modes nil) does not work as expected. For example given the test code:

```elisp
;; test.el
(package-initialize)

;; straight.el initialization
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 6))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))

;; Location of my use-package git clone
(add-to-list 'load-path "~/.emacs.d/.local/straight/repos/use-package/")
(require 'use-package)

(use-package mini-echo
  :ensure t)

(use-package dash
  :ensure t)

(use-package hide-mode-line
  :ensure t)

(use-package eglot
  :ensure t)

(setq hide-mode-line-excluded-modes nil)

(add-hook 'python-mode-hook 'eglot-ensure)

(global-hide-mode-line-mode)
```
First open emacs with:

```shell
emacs -Q -l test.el 
```

Then use 
C-x C-f to find the test.py under the directory.

Then use 
C-x C-b to find the eglot buffer, I can still see the modeline 
![image](https://github.com/user-attachments/assets/4e08ec51-40e7-429c-aa7e-a0df7a848db3)

Same if we change (global-hide-mode-line-mode) to (mini-echo-mode).

I see the commit you did yesterday, and I think it does ensure when mini-echo-mode is toggled, all modelines would be disabled, however, if we open another buffer with fundamental mode, the modeline will show up.

I might also mention this issue in the hide-mode-line repo to see if there is any way to solve it.

Again, thank you for your great package and response!

**Comment by liuyinz** [comment]
Actually it's not a bug. According to [Defining-Minor-Mode](https://www.gnu.org/software/emacs/manual/html_node/elisp/Defining-Minor-Modes.html#index-define_002dglobalized_002dminor_002dmode),

> Globally enabling the mode also affects buffers subsequently created by visiting files, and buffers that use a major mode other than Fundamental mode; but it does not detect the creation of a new buffer in Fundamental mode.

Turn on `global-hide-mode-line-mode` doesn't take effect in fundamental-mode buffers by default. But in practise it works intermittently. so I add a timer to enable in all failed buffers.

After latest commit, there is no problem in my config, even open a new fundamental-mode buffer is OK.  So are you sure it doesn't work in your machine ?

**Comment by JiaweiChenC** [comment]
Thank you again for your reply! You are right, this is not a fundamental-mode buffer issue. I think it is a problem in special buffer with fundamental mode(such as the \*EGLOT\* buffer I mentioned above).  A new commit from https://github.com/hlissner/emacs-hide-mode-line/commit/ab699fdcbd43f2d043d588091694a272367901bd solved the problem partially (now if I enable global-hide-mode-line-mode manually after emacs init, the special buffer created ( like \*EGLOG\*) will not have modeline). 

However, if I only enable mini-echo mode in my config, the new special buffer created will still have modeline with it. Since there are several tricks in both packages, now it is behaving weirdly and I cannot locate the problem myself. For example, if I init global-hide-mode-line-mode in the config file, it seems the special buffer created will still have mode-line with it, while init global-hide-mode-line-mode manually after init will not. 

Did you try to use the file above to reproduce the issue? If it is fine on your end, maybe its a issue in my config or other packages.

Thank you for your time!

**Comment by liuyinz** [comment]
I use the latest emacs@31.0.50 on cocoa OSX platform, and everything is fine. Which version are you using ? I guess your bug maybe related to emacs version or platform.

**Comment by JiaweiChenC** [comment]
I see. I am using emacs@29.4 on macos. I will try to build emacs@30 or 31 and see if that solves the problem. Thanks!
