### ISSUE TITLE
Please consider to create releases or at least pull requests

### ISSUE THREAD

**Issue by Crandel** [liuyinz/mini-echo.el#17]
Thank you for this amazing project I use since last year everyday. 
I have only one suggestion for you. 

Please consider to create releases or at least pull requests, as it is hard to view every commit in order to check for new features or some major changes. I've been recently updating this package and found it not working correctly, because some changes, so I dig around one hour in git history in order to figure out what was the change.

**Comment by liuyinz** [comment]
v1.0 will be released in the coming days, as the first stable version。 Readme and release notes will be thoroughly revised and enhanced. Thans for your advice.

**Comment by liuyinz** [comment]
README has beeb updated ! check it if you need.
