### ISSUE TITLE
Wrong type argument: listp, "major-mode" when running ibuffer

### ISSUE THREAD

**Issue by nowislewis** [liuyinz/mini-echo.el#19]
Currently, when I run ibuffer, I encounter the following error:
```
mini-echo-normalize-rule: Wrong type argument: listp, "major-mode".
```
However, if I remove the check for ibuffer-mode in mini-echo-persistent-detect, everything works smoothly.

I am truly grateful for the mini-echo project; I have been using it for quite some time, and it has served my excellently!

**Comment by liuyinz** [comment]
fixed already, update to latest and check it.

**Comment by nowislewis** [comment]
Great!
