### ISSUE TITLE
Convenient functions to add/remove segments?

### ISSUE THREAD

**Issue by oscarfv** [liuyinz/mini-echo.el#23]
Maybe I'm missing something obvious, but are there any functions that I can use in my `.emacs.el` for adding or removing segments from `mini-echo-persistent-rule` and `mini-echo-temporary-rule`?. The only way I can see on the docs is to use `setq mini-echo-temporary-rule <new-value>)` but the problem with this is that I'm overwriting the default contents of the variable when I  just want to add or remove the segment that interests me.

A function or functions would simplify things a lot:

```
(mini-echo-remove-persistent-rule "selection-info" ':long)
(mini-echo-add-persistent-rule "my-segment" ':short)
```

Doing an explicit `(setf ...` or `(setq ...` to add/remove the segment is a mouthful and not future-proof at all. Right now I'm using `mini-echo-toggle` for the same segments every time I start Emacs.

**Comment by liuyinz** [comment]
Why not just `(setq mini-echo-persistent-rule ...)` ? these two variables are setup as fallback if function `mini-echo-persistent-function` return nil, and only calling once when you initiaize emacs, I don't get what mouthful means.

**Comment by liuyinz** [comment]
The key point lies in the order of the segments. Adding such adding/removing function is not difficult, but it requires importing both the style and index args, unnecessarily increasing complexity I think. You can wrap a command for your own need.

**Comment by oscarfv** [comment]
I don't know what the style and index args are, since I don't know enough about `mini-echo` source, but anyway here is my half-assed implementation, just for the record:

```
(defun mini-echo-remove-segment (segment &optional rule prop)
    "Removes SEGMENT from the property PROP of RULE.

If RULE is nil, remove SEGMENT from all rules.

If PROP is nil, remove SEGMENT from all properties."
    (cond 
     ((not rule)
      (mini-echo-remove-segment segment mini-echo-temporary-rule prop)
      (mini-echo-remove-segment segment mini-echo-persistent-rule prop))
     ((not prop)
      (dolist (p '(:long :short :both))
	(mini-echo-remove-segment segment rule p)))
     (t
      (when-let ((value (plist-get rule prop)))
	(setq value (delete segment value))
	(setq rule (plist-put rule prop value))))))

(defun mini-echo-add-segment (segment rule prop &optional after)
    "Inserts SEGMENT into the property PROP of RULE.

If AFTER is non-nil, SEGMENT is inserted after AFTER if it exists.
Otherwise insert it at the front.

SEGMENT is removed from the property PROP of RULE before the insertion."
    (let* ((value (plist-get rule prop))
	   (found))
      (setq value (delete segment value))
      (while (and after (car value) (not found))
	(if (equal (car value) after)
	    (progn
	      (setq found t)
	      (setcdr value (cons segment (cdr value))))
	  (setq value (cdr value))))
      (unless found
	(push segment value))
      (setq rule (plist-put rule prop value))))
```

Example:

```
(mini-echo-remove-segment "selection-info")

(mini-echo-define-segment "say-hi"
    "Say hi!."
    :fetch "Hi!")
(mini-echo-add-segment "say-hi" mini-echo-persistent-rule :long "major-mode")
```
