### ISSUE TITLE
Add lsp-modeline integration

### ISSUE THREAD

**Issue by Crandel** [liuyinz/mini-echo.el#3]
According to [lsp docs](https://emacs-lsp.github.io/lsp-mode/page/main-features/#project-errors-on-modeline) it is possible to show project errors in modeline. 

Would be nice to extend already implemented lsp segment or add lsp-errors segment with same integration.

**Comment by liuyinz** [comment]
Does lsp-mode show diagnostics information by using flymake/flycheck frontend? I'm not familiar with lsp-mode, but it seems it's OK according to [README](https://github.com/emacs-lsp/lsp-mode#overview)

**Comment by Crandel** [comment]
I guess you can find an example here, if I correctly understand doom-modeline src code. But I could be mistaken as I have very little elisp understanding.
https://github.com/seagle0128/doom-modeline/blob/master/doom-modeline-segments.el#L2032

**Comment by Crandel** [comment]
In modeline it just shows error/warning count like on this image
https://emacs-lsp.github.io/lsp-mode/examples/modeline-diagnostics.png

**Comment by liuyinz** [comment]
Oh, I understand it. No, mini-echo don't implement these complicated features, maybe  doom-modeline  are better for you. @Crandel

**Comment by Crandel** [comment]
I finally figure out how to show lsp diagnostics errors in flymake

I need to explicitly set 

```lisp
  (setq lsp-diagnostics-provider :flymake)
```

Now everything is working with flymake segment
