### ISSUE TITLE
Can NOT read text with light theme

### ISSUE THREAD

**Issue by cabins** [liuyinz/mini-echo.el#4]
![image](https://github.com/liuyinz/mini-echo.el/assets/2500123/5549e88b-dcbe-40dd-906c-0b43c684cb30)

**Comment by liuyinz** [comment]
After fe6d3f35d124f9b4fc0d3ce77f68557c4ae7f4c0 to use default background color by default, please update to latest and check whether the problem exists.

**Comment by liuyinz** [comment]
@jvillasante melpa source has been updated. So you could update it from that directly.

**Comment by cabins** [comment]
Yes! The latest version works perfectly. Awesome work!
