### ISSUE TITLE
Issue when loading theme twice or other theme

### ISSUE THREAD

**Issue by idlip** [liuyinz/mini-echo.el#6]
When you load a theme or change when `mini-echo-mode` is active, it create weird duplicate line displaying those messages again, if you reload any or same theme again `(load-theme 'modus-vivendi t)`, emacs gets slow and you need to manually run `M-x mini-echo-mode` to get it to proper working display.

Specs: 
Emacs GNU Emacs 29.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.38, cairo version 1.16.0)
Pgtk build in Wayland

To reproduce:
1. Run `(load-theme 'modus-vivendi t)` twice and so

![mini-echo](https://github.com/liuyinz/mini-echo.el/assets/117019901/faa156f0-2ce1-4aa1-8e38-2593ec518981)

Here is the respective attached image.

**Comment by liuyinz** [comment]
I cann't  reproduce this behavior, could you provide a minimal config ? Please update package to latest and delete -autolaod.el, elc, eln of mini-echo then test it again.

**Comment by idlip** [comment]
My bad, did not try with `emacs -Q`

But even with `emacs -Q`, I see this behavior, I mean that starts with no config, only vanilla emacs right?

Here is the video of duplicate occuring, but it will revert back when i toggle `mini-echo-mode` twice.

https://github.com/liuyinz/mini-echo.el/assets/117019901/c9020814-bf5c-4f8e-b087-30317a1e1de8

**Comment by liuyinz** [comment]
@idlip  I can reproduce it now.

**Comment by liuyinz** [comment]
@idlip please update to latest 5c43d10138cb7911138a42d054dae0fc11bc7146 commit and check whether the problem solved

**Comment by idlip** [comment]
Thank you for resolving this, issue is solved with latest changes.

**Comment by idlip** [comment]
@liuyinz Also there is small correction in battery segment function, @ 394 line

```emacs-lisp
(mini-echo-define-segment "battery"
  "Return the battery status.
Display format is inherited from `battery-mode-line-format'."
  :setup (display-battery-mode 1)
  :fetch
  (propertize (string-trim
               (battery-format battery-mode-line-format
                               (funcall battery-status-function)) ;; needs ')' to enclose string-trim functiong
               'face 'mini-echo-battery))) ;; need to remove one ')' here 
```

we get `wrong type sequencep error`

**Comment by liuyinz** [comment]
@idlip solved.
