### ISSUE TITLE
Upgrade to version 0.62 but get the following error: "seq-keep: Symbol's function definition is void: derived-mode-all-parents"

### ISSUE THREAD

**Issue by xplutoy** [liuyinz/mini-echo.el#7]
emacs-version: 
GNU Emacs 29.1.50 (build 2, x86_64-apple-darwin21.6.0, NS appkit-2113.60 Version 12.6.5 (Build 21G531)) of 2023-08-04

**Comment by liuyinz** [comment]
could you find definition in your emacs by `M-x describe-function derived-mode-all-parents` ? Maybe this function is added  in emacs 30...

**Comment by liuyinz** [comment]
@xplutoy update to latest and check it
